/*  .file eagine/math/vector_swizzles.ipp
 *  Automatically generated file do not modify manually.
 *  Copyright 2014-2015 Matus Chochlik. Distributed under the Boost
 *  Software License, Version 1.0. (See accompanying file
 *  LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
 */
BOOST_ASSERT((v.Ox(c) == eagine::math::tvec<T,2,V>(c, v.x())));
BOOST_ASSERT((v.Oy(c) == eagine::math::tvec<T,2,V>(c, v.y())));
BOOST_ASSERT((v.Oz(c) == eagine::math::tvec<T,2,V>(c, v.z())));
BOOST_ASSERT((v.Ow(c) == eagine::math::tvec<T,2,V>(c, v.w())));
BOOST_ASSERT((v.xO(c) == eagine::math::tvec<T,2,V>(v.x(), c)));
BOOST_ASSERT((v.xx(c) == eagine::math::tvec<T,2,V>(v.x(), v.x())));
BOOST_ASSERT((v.xy(c) == eagine::math::tvec<T,2,V>(v.x(), v.y())));
BOOST_ASSERT((v.xz(c) == eagine::math::tvec<T,2,V>(v.x(), v.z())));
BOOST_ASSERT((v.xw(c) == eagine::math::tvec<T,2,V>(v.x(), v.w())));
BOOST_ASSERT((v.yO(c) == eagine::math::tvec<T,2,V>(v.y(), c)));
BOOST_ASSERT((v.yx(c) == eagine::math::tvec<T,2,V>(v.y(), v.x())));
BOOST_ASSERT((v.yy(c) == eagine::math::tvec<T,2,V>(v.y(), v.y())));
BOOST_ASSERT((v.yz(c) == eagine::math::tvec<T,2,V>(v.y(), v.z())));
BOOST_ASSERT((v.yw(c) == eagine::math::tvec<T,2,V>(v.y(), v.w())));
BOOST_ASSERT((v.zO(c) == eagine::math::tvec<T,2,V>(v.z(), c)));
BOOST_ASSERT((v.zx(c) == eagine::math::tvec<T,2,V>(v.z(), v.x())));
BOOST_ASSERT((v.zy(c) == eagine::math::tvec<T,2,V>(v.z(), v.y())));
BOOST_ASSERT((v.zz(c) == eagine::math::tvec<T,2,V>(v.z(), v.z())));
BOOST_ASSERT((v.zw(c) == eagine::math::tvec<T,2,V>(v.z(), v.w())));
BOOST_ASSERT((v.wO(c) == eagine::math::tvec<T,2,V>(v.w(), c)));
BOOST_ASSERT((v.wx(c) == eagine::math::tvec<T,2,V>(v.w(), v.x())));
BOOST_ASSERT((v.wy(c) == eagine::math::tvec<T,2,V>(v.w(), v.y())));
BOOST_ASSERT((v.wz(c) == eagine::math::tvec<T,2,V>(v.w(), v.z())));
BOOST_ASSERT((v.ww(c) == eagine::math::tvec<T,2,V>(v.w(), v.w())));
BOOST_ASSERT((v.OOx(c) == eagine::math::tvec<T,3,V>(c, c, v.x())));
BOOST_ASSERT((v.OOy(c) == eagine::math::tvec<T,3,V>(c, c, v.y())));
BOOST_ASSERT((v.OOz(c) == eagine::math::tvec<T,3,V>(c, c, v.z())));
BOOST_ASSERT((v.OOw(c) == eagine::math::tvec<T,3,V>(c, c, v.w())));
BOOST_ASSERT((v.OxO(c) == eagine::math::tvec<T,3,V>(c, v.x(), c)));
BOOST_ASSERT((v.Oxx(c) == eagine::math::tvec<T,3,V>(c, v.x(), v.x())));
BOOST_ASSERT((v.Oxy(c) == eagine::math::tvec<T,3,V>(c, v.x(), v.y())));
BOOST_ASSERT((v.Oxz(c) == eagine::math::tvec<T,3,V>(c, v.x(), v.z())));
BOOST_ASSERT((v.Oxw(c) == eagine::math::tvec<T,3,V>(c, v.x(), v.w())));
BOOST_ASSERT((v.OyO(c) == eagine::math::tvec<T,3,V>(c, v.y(), c)));
BOOST_ASSERT((v.Oyx(c) == eagine::math::tvec<T,3,V>(c, v.y(), v.x())));
BOOST_ASSERT((v.Oyy(c) == eagine::math::tvec<T,3,V>(c, v.y(), v.y())));
BOOST_ASSERT((v.Oyz(c) == eagine::math::tvec<T,3,V>(c, v.y(), v.z())));
BOOST_ASSERT((v.Oyw(c) == eagine::math::tvec<T,3,V>(c, v.y(), v.w())));
BOOST_ASSERT((v.OzO(c) == eagine::math::tvec<T,3,V>(c, v.z(), c)));
BOOST_ASSERT((v.Ozx(c) == eagine::math::tvec<T,3,V>(c, v.z(), v.x())));
BOOST_ASSERT((v.Ozy(c) == eagine::math::tvec<T,3,V>(c, v.z(), v.y())));
BOOST_ASSERT((v.Ozz(c) == eagine::math::tvec<T,3,V>(c, v.z(), v.z())));
BOOST_ASSERT((v.Ozw(c) == eagine::math::tvec<T,3,V>(c, v.z(), v.w())));
BOOST_ASSERT((v.OwO(c) == eagine::math::tvec<T,3,V>(c, v.w(), c)));
BOOST_ASSERT((v.Owx(c) == eagine::math::tvec<T,3,V>(c, v.w(), v.x())));
BOOST_ASSERT((v.Owy(c) == eagine::math::tvec<T,3,V>(c, v.w(), v.y())));
BOOST_ASSERT((v.Owz(c) == eagine::math::tvec<T,3,V>(c, v.w(), v.z())));
BOOST_ASSERT((v.Oww(c) == eagine::math::tvec<T,3,V>(c, v.w(), v.w())));
BOOST_ASSERT((v.xOO(c) == eagine::math::tvec<T,3,V>(v.x(), c, c)));
BOOST_ASSERT((v.xOx(c) == eagine::math::tvec<T,3,V>(v.x(), c, v.x())));
BOOST_ASSERT((v.xOy(c) == eagine::math::tvec<T,3,V>(v.x(), c, v.y())));
BOOST_ASSERT((v.xOz(c) == eagine::math::tvec<T,3,V>(v.x(), c, v.z())));
BOOST_ASSERT((v.xOw(c) == eagine::math::tvec<T,3,V>(v.x(), c, v.w())));
BOOST_ASSERT((v.xxO(c) == eagine::math::tvec<T,3,V>(v.x(), v.x(), c)));
BOOST_ASSERT((v.xxx(c) == eagine::math::tvec<T,3,V>(v.x(), v.x(), v.x())));
BOOST_ASSERT((v.xxy(c) == eagine::math::tvec<T,3,V>(v.x(), v.x(), v.y())));
BOOST_ASSERT((v.xxz(c) == eagine::math::tvec<T,3,V>(v.x(), v.x(), v.z())));
BOOST_ASSERT((v.xxw(c) == eagine::math::tvec<T,3,V>(v.x(), v.x(), v.w())));
BOOST_ASSERT((v.xyO(c) == eagine::math::tvec<T,3,V>(v.x(), v.y(), c)));
BOOST_ASSERT((v.xyx(c) == eagine::math::tvec<T,3,V>(v.x(), v.y(), v.x())));
BOOST_ASSERT((v.xyy(c) == eagine::math::tvec<T,3,V>(v.x(), v.y(), v.y())));
BOOST_ASSERT((v.xyz(c) == eagine::math::tvec<T,3,V>(v.x(), v.y(), v.z())));
BOOST_ASSERT((v.xyw(c) == eagine::math::tvec<T,3,V>(v.x(), v.y(), v.w())));
BOOST_ASSERT((v.xzO(c) == eagine::math::tvec<T,3,V>(v.x(), v.z(), c)));
BOOST_ASSERT((v.xzx(c) == eagine::math::tvec<T,3,V>(v.x(), v.z(), v.x())));
BOOST_ASSERT((v.xzy(c) == eagine::math::tvec<T,3,V>(v.x(), v.z(), v.y())));
BOOST_ASSERT((v.xzz(c) == eagine::math::tvec<T,3,V>(v.x(), v.z(), v.z())));
BOOST_ASSERT((v.xzw(c) == eagine::math::tvec<T,3,V>(v.x(), v.z(), v.w())));
BOOST_ASSERT((v.xwO(c) == eagine::math::tvec<T,3,V>(v.x(), v.w(), c)));
BOOST_ASSERT((v.xwx(c) == eagine::math::tvec<T,3,V>(v.x(), v.w(), v.x())));
BOOST_ASSERT((v.xwy(c) == eagine::math::tvec<T,3,V>(v.x(), v.w(), v.y())));
BOOST_ASSERT((v.xwz(c) == eagine::math::tvec<T,3,V>(v.x(), v.w(), v.z())));
BOOST_ASSERT((v.xww(c) == eagine::math::tvec<T,3,V>(v.x(), v.w(), v.w())));
BOOST_ASSERT((v.yOO(c) == eagine::math::tvec<T,3,V>(v.y(), c, c)));
BOOST_ASSERT((v.yOx(c) == eagine::math::tvec<T,3,V>(v.y(), c, v.x())));
BOOST_ASSERT((v.yOy(c) == eagine::math::tvec<T,3,V>(v.y(), c, v.y())));
BOOST_ASSERT((v.yOz(c) == eagine::math::tvec<T,3,V>(v.y(), c, v.z())));
BOOST_ASSERT((v.yOw(c) == eagine::math::tvec<T,3,V>(v.y(), c, v.w())));
BOOST_ASSERT((v.yxO(c) == eagine::math::tvec<T,3,V>(v.y(), v.x(), c)));
BOOST_ASSERT((v.yxx(c) == eagine::math::tvec<T,3,V>(v.y(), v.x(), v.x())));
BOOST_ASSERT((v.yxy(c) == eagine::math::tvec<T,3,V>(v.y(), v.x(), v.y())));
BOOST_ASSERT((v.yxz(c) == eagine::math::tvec<T,3,V>(v.y(), v.x(), v.z())));
BOOST_ASSERT((v.yxw(c) == eagine::math::tvec<T,3,V>(v.y(), v.x(), v.w())));
BOOST_ASSERT((v.yyO(c) == eagine::math::tvec<T,3,V>(v.y(), v.y(), c)));
BOOST_ASSERT((v.yyx(c) == eagine::math::tvec<T,3,V>(v.y(), v.y(), v.x())));
BOOST_ASSERT((v.yyy(c) == eagine::math::tvec<T,3,V>(v.y(), v.y(), v.y())));
BOOST_ASSERT((v.yyz(c) == eagine::math::tvec<T,3,V>(v.y(), v.y(), v.z())));
BOOST_ASSERT((v.yyw(c) == eagine::math::tvec<T,3,V>(v.y(), v.y(), v.w())));
BOOST_ASSERT((v.yzO(c) == eagine::math::tvec<T,3,V>(v.y(), v.z(), c)));
BOOST_ASSERT((v.yzx(c) == eagine::math::tvec<T,3,V>(v.y(), v.z(), v.x())));
BOOST_ASSERT((v.yzy(c) == eagine::math::tvec<T,3,V>(v.y(), v.z(), v.y())));
BOOST_ASSERT((v.yzz(c) == eagine::math::tvec<T,3,V>(v.y(), v.z(), v.z())));
BOOST_ASSERT((v.yzw(c) == eagine::math::tvec<T,3,V>(v.y(), v.z(), v.w())));
BOOST_ASSERT((v.ywO(c) == eagine::math::tvec<T,3,V>(v.y(), v.w(), c)));
BOOST_ASSERT((v.ywx(c) == eagine::math::tvec<T,3,V>(v.y(), v.w(), v.x())));
BOOST_ASSERT((v.ywy(c) == eagine::math::tvec<T,3,V>(v.y(), v.w(), v.y())));
BOOST_ASSERT((v.ywz(c) == eagine::math::tvec<T,3,V>(v.y(), v.w(), v.z())));
BOOST_ASSERT((v.yww(c) == eagine::math::tvec<T,3,V>(v.y(), v.w(), v.w())));
BOOST_ASSERT((v.zOO(c) == eagine::math::tvec<T,3,V>(v.z(), c, c)));
BOOST_ASSERT((v.zOx(c) == eagine::math::tvec<T,3,V>(v.z(), c, v.x())));
BOOST_ASSERT((v.zOy(c) == eagine::math::tvec<T,3,V>(v.z(), c, v.y())));
BOOST_ASSERT((v.zOz(c) == eagine::math::tvec<T,3,V>(v.z(), c, v.z())));
BOOST_ASSERT((v.zOw(c) == eagine::math::tvec<T,3,V>(v.z(), c, v.w())));
BOOST_ASSERT((v.zxO(c) == eagine::math::tvec<T,3,V>(v.z(), v.x(), c)));
BOOST_ASSERT((v.zxx(c) == eagine::math::tvec<T,3,V>(v.z(), v.x(), v.x())));
BOOST_ASSERT((v.zxy(c) == eagine::math::tvec<T,3,V>(v.z(), v.x(), v.y())));
BOOST_ASSERT((v.zxz(c) == eagine::math::tvec<T,3,V>(v.z(), v.x(), v.z())));
BOOST_ASSERT((v.zxw(c) == eagine::math::tvec<T,3,V>(v.z(), v.x(), v.w())));
BOOST_ASSERT((v.zyO(c) == eagine::math::tvec<T,3,V>(v.z(), v.y(), c)));
BOOST_ASSERT((v.zyx(c) == eagine::math::tvec<T,3,V>(v.z(), v.y(), v.x())));
BOOST_ASSERT((v.zyy(c) == eagine::math::tvec<T,3,V>(v.z(), v.y(), v.y())));
BOOST_ASSERT((v.zyz(c) == eagine::math::tvec<T,3,V>(v.z(), v.y(), v.z())));
BOOST_ASSERT((v.zyw(c) == eagine::math::tvec<T,3,V>(v.z(), v.y(), v.w())));
BOOST_ASSERT((v.zzO(c) == eagine::math::tvec<T,3,V>(v.z(), v.z(), c)));
BOOST_ASSERT((v.zzx(c) == eagine::math::tvec<T,3,V>(v.z(), v.z(), v.x())));
BOOST_ASSERT((v.zzy(c) == eagine::math::tvec<T,3,V>(v.z(), v.z(), v.y())));
BOOST_ASSERT((v.zzz(c) == eagine::math::tvec<T,3,V>(v.z(), v.z(), v.z())));
BOOST_ASSERT((v.zzw(c) == eagine::math::tvec<T,3,V>(v.z(), v.z(), v.w())));
BOOST_ASSERT((v.zwO(c) == eagine::math::tvec<T,3,V>(v.z(), v.w(), c)));
BOOST_ASSERT((v.zwx(c) == eagine::math::tvec<T,3,V>(v.z(), v.w(), v.x())));
BOOST_ASSERT((v.zwy(c) == eagine::math::tvec<T,3,V>(v.z(), v.w(), v.y())));
BOOST_ASSERT((v.zwz(c) == eagine::math::tvec<T,3,V>(v.z(), v.w(), v.z())));
BOOST_ASSERT((v.zww(c) == eagine::math::tvec<T,3,V>(v.z(), v.w(), v.w())));
BOOST_ASSERT((v.wOO(c) == eagine::math::tvec<T,3,V>(v.w(), c, c)));
BOOST_ASSERT((v.wOx(c) == eagine::math::tvec<T,3,V>(v.w(), c, v.x())));
BOOST_ASSERT((v.wOy(c) == eagine::math::tvec<T,3,V>(v.w(), c, v.y())));
BOOST_ASSERT((v.wOz(c) == eagine::math::tvec<T,3,V>(v.w(), c, v.z())));
BOOST_ASSERT((v.wOw(c) == eagine::math::tvec<T,3,V>(v.w(), c, v.w())));
BOOST_ASSERT((v.wxO(c) == eagine::math::tvec<T,3,V>(v.w(), v.x(), c)));
BOOST_ASSERT((v.wxx(c) == eagine::math::tvec<T,3,V>(v.w(), v.x(), v.x())));
BOOST_ASSERT((v.wxy(c) == eagine::math::tvec<T,3,V>(v.w(), v.x(), v.y())));
BOOST_ASSERT((v.wxz(c) == eagine::math::tvec<T,3,V>(v.w(), v.x(), v.z())));
BOOST_ASSERT((v.wxw(c) == eagine::math::tvec<T,3,V>(v.w(), v.x(), v.w())));
BOOST_ASSERT((v.wyO(c) == eagine::math::tvec<T,3,V>(v.w(), v.y(), c)));
BOOST_ASSERT((v.wyx(c) == eagine::math::tvec<T,3,V>(v.w(), v.y(), v.x())));
BOOST_ASSERT((v.wyy(c) == eagine::math::tvec<T,3,V>(v.w(), v.y(), v.y())));
BOOST_ASSERT((v.wyz(c) == eagine::math::tvec<T,3,V>(v.w(), v.y(), v.z())));
BOOST_ASSERT((v.wyw(c) == eagine::math::tvec<T,3,V>(v.w(), v.y(), v.w())));
BOOST_ASSERT((v.wzO(c) == eagine::math::tvec<T,3,V>(v.w(), v.z(), c)));
BOOST_ASSERT((v.wzx(c) == eagine::math::tvec<T,3,V>(v.w(), v.z(), v.x())));
BOOST_ASSERT((v.wzy(c) == eagine::math::tvec<T,3,V>(v.w(), v.z(), v.y())));
BOOST_ASSERT((v.wzz(c) == eagine::math::tvec<T,3,V>(v.w(), v.z(), v.z())));
BOOST_ASSERT((v.wzw(c) == eagine::math::tvec<T,3,V>(v.w(), v.z(), v.w())));
BOOST_ASSERT((v.wwO(c) == eagine::math::tvec<T,3,V>(v.w(), v.w(), c)));
BOOST_ASSERT((v.wwx(c) == eagine::math::tvec<T,3,V>(v.w(), v.w(), v.x())));
BOOST_ASSERT((v.wwy(c) == eagine::math::tvec<T,3,V>(v.w(), v.w(), v.y())));
BOOST_ASSERT((v.wwz(c) == eagine::math::tvec<T,3,V>(v.w(), v.w(), v.z())));
BOOST_ASSERT((v.www(c) == eagine::math::tvec<T,3,V>(v.w(), v.w(), v.w())));
BOOST_ASSERT((v.OOOx(c) == eagine::math::tvec<T,4,V>(c, c, c, v.x())));
BOOST_ASSERT((v.OOOy(c) == eagine::math::tvec<T,4,V>(c, c, c, v.y())));
BOOST_ASSERT((v.OOOz(c) == eagine::math::tvec<T,4,V>(c, c, c, v.z())));
BOOST_ASSERT((v.OOOw(c) == eagine::math::tvec<T,4,V>(c, c, c, v.w())));
BOOST_ASSERT((v.OOxO(c) == eagine::math::tvec<T,4,V>(c, c, v.x(), c)));
BOOST_ASSERT((v.OOxx(c) == eagine::math::tvec<T,4,V>(c, c, v.x(), v.x())));
BOOST_ASSERT((v.OOxy(c) == eagine::math::tvec<T,4,V>(c, c, v.x(), v.y())));
BOOST_ASSERT((v.OOxz(c) == eagine::math::tvec<T,4,V>(c, c, v.x(), v.z())));
BOOST_ASSERT((v.OOxw(c) == eagine::math::tvec<T,4,V>(c, c, v.x(), v.w())));
BOOST_ASSERT((v.OOyO(c) == eagine::math::tvec<T,4,V>(c, c, v.y(), c)));
BOOST_ASSERT((v.OOyx(c) == eagine::math::tvec<T,4,V>(c, c, v.y(), v.x())));
BOOST_ASSERT((v.OOyy(c) == eagine::math::tvec<T,4,V>(c, c, v.y(), v.y())));
BOOST_ASSERT((v.OOyz(c) == eagine::math::tvec<T,4,V>(c, c, v.y(), v.z())));
BOOST_ASSERT((v.OOyw(c) == eagine::math::tvec<T,4,V>(c, c, v.y(), v.w())));
BOOST_ASSERT((v.OOzO(c) == eagine::math::tvec<T,4,V>(c, c, v.z(), c)));
BOOST_ASSERT((v.OOzx(c) == eagine::math::tvec<T,4,V>(c, c, v.z(), v.x())));
BOOST_ASSERT((v.OOzy(c) == eagine::math::tvec<T,4,V>(c, c, v.z(), v.y())));
BOOST_ASSERT((v.OOzz(c) == eagine::math::tvec<T,4,V>(c, c, v.z(), v.z())));
BOOST_ASSERT((v.OOzw(c) == eagine::math::tvec<T,4,V>(c, c, v.z(), v.w())));
BOOST_ASSERT((v.OOwO(c) == eagine::math::tvec<T,4,V>(c, c, v.w(), c)));
BOOST_ASSERT((v.OOwx(c) == eagine::math::tvec<T,4,V>(c, c, v.w(), v.x())));
BOOST_ASSERT((v.OOwy(c) == eagine::math::tvec<T,4,V>(c, c, v.w(), v.y())));
BOOST_ASSERT((v.OOwz(c) == eagine::math::tvec<T,4,V>(c, c, v.w(), v.z())));
BOOST_ASSERT((v.OOww(c) == eagine::math::tvec<T,4,V>(c, c, v.w(), v.w())));
BOOST_ASSERT((v.OxOO(c) == eagine::math::tvec<T,4,V>(c, v.x(), c, c)));
BOOST_ASSERT((v.OxOx(c) == eagine::math::tvec<T,4,V>(c, v.x(), c, v.x())));
BOOST_ASSERT((v.OxOy(c) == eagine::math::tvec<T,4,V>(c, v.x(), c, v.y())));
BOOST_ASSERT((v.OxOz(c) == eagine::math::tvec<T,4,V>(c, v.x(), c, v.z())));
BOOST_ASSERT((v.OxOw(c) == eagine::math::tvec<T,4,V>(c, v.x(), c, v.w())));
BOOST_ASSERT((v.OxxO(c) == eagine::math::tvec<T,4,V>(c, v.x(), v.x(), c)));
BOOST_ASSERT((v.Oxxx(c) == eagine::math::tvec<T,4,V>(c, v.x(), v.x(), v.x())));
BOOST_ASSERT((v.Oxxy(c) == eagine::math::tvec<T,4,V>(c, v.x(), v.x(), v.y())));
BOOST_ASSERT((v.Oxxz(c) == eagine::math::tvec<T,4,V>(c, v.x(), v.x(), v.z())));
BOOST_ASSERT((v.Oxxw(c) == eagine::math::tvec<T,4,V>(c, v.x(), v.x(), v.w())));
BOOST_ASSERT((v.OxyO(c) == eagine::math::tvec<T,4,V>(c, v.x(), v.y(), c)));
BOOST_ASSERT((v.Oxyx(c) == eagine::math::tvec<T,4,V>(c, v.x(), v.y(), v.x())));
BOOST_ASSERT((v.Oxyy(c) == eagine::math::tvec<T,4,V>(c, v.x(), v.y(), v.y())));
BOOST_ASSERT((v.Oxyz(c) == eagine::math::tvec<T,4,V>(c, v.x(), v.y(), v.z())));
BOOST_ASSERT((v.Oxyw(c) == eagine::math::tvec<T,4,V>(c, v.x(), v.y(), v.w())));
BOOST_ASSERT((v.OxzO(c) == eagine::math::tvec<T,4,V>(c, v.x(), v.z(), c)));
BOOST_ASSERT((v.Oxzx(c) == eagine::math::tvec<T,4,V>(c, v.x(), v.z(), v.x())));
BOOST_ASSERT((v.Oxzy(c) == eagine::math::tvec<T,4,V>(c, v.x(), v.z(), v.y())));
BOOST_ASSERT((v.Oxzz(c) == eagine::math::tvec<T,4,V>(c, v.x(), v.z(), v.z())));
BOOST_ASSERT((v.Oxzw(c) == eagine::math::tvec<T,4,V>(c, v.x(), v.z(), v.w())));
BOOST_ASSERT((v.OxwO(c) == eagine::math::tvec<T,4,V>(c, v.x(), v.w(), c)));
BOOST_ASSERT((v.Oxwx(c) == eagine::math::tvec<T,4,V>(c, v.x(), v.w(), v.x())));
BOOST_ASSERT((v.Oxwy(c) == eagine::math::tvec<T,4,V>(c, v.x(), v.w(), v.y())));
BOOST_ASSERT((v.Oxwz(c) == eagine::math::tvec<T,4,V>(c, v.x(), v.w(), v.z())));
BOOST_ASSERT((v.Oxww(c) == eagine::math::tvec<T,4,V>(c, v.x(), v.w(), v.w())));
BOOST_ASSERT((v.OyOO(c) == eagine::math::tvec<T,4,V>(c, v.y(), c, c)));
BOOST_ASSERT((v.OyOx(c) == eagine::math::tvec<T,4,V>(c, v.y(), c, v.x())));
BOOST_ASSERT((v.OyOy(c) == eagine::math::tvec<T,4,V>(c, v.y(), c, v.y())));
BOOST_ASSERT((v.OyOz(c) == eagine::math::tvec<T,4,V>(c, v.y(), c, v.z())));
BOOST_ASSERT((v.OyOw(c) == eagine::math::tvec<T,4,V>(c, v.y(), c, v.w())));
BOOST_ASSERT((v.OyxO(c) == eagine::math::tvec<T,4,V>(c, v.y(), v.x(), c)));
BOOST_ASSERT((v.Oyxx(c) == eagine::math::tvec<T,4,V>(c, v.y(), v.x(), v.x())));
BOOST_ASSERT((v.Oyxy(c) == eagine::math::tvec<T,4,V>(c, v.y(), v.x(), v.y())));
BOOST_ASSERT((v.Oyxz(c) == eagine::math::tvec<T,4,V>(c, v.y(), v.x(), v.z())));
BOOST_ASSERT((v.Oyxw(c) == eagine::math::tvec<T,4,V>(c, v.y(), v.x(), v.w())));
BOOST_ASSERT((v.OyyO(c) == eagine::math::tvec<T,4,V>(c, v.y(), v.y(), c)));
BOOST_ASSERT((v.Oyyx(c) == eagine::math::tvec<T,4,V>(c, v.y(), v.y(), v.x())));
BOOST_ASSERT((v.Oyyy(c) == eagine::math::tvec<T,4,V>(c, v.y(), v.y(), v.y())));
BOOST_ASSERT((v.Oyyz(c) == eagine::math::tvec<T,4,V>(c, v.y(), v.y(), v.z())));
BOOST_ASSERT((v.Oyyw(c) == eagine::math::tvec<T,4,V>(c, v.y(), v.y(), v.w())));
BOOST_ASSERT((v.OyzO(c) == eagine::math::tvec<T,4,V>(c, v.y(), v.z(), c)));
BOOST_ASSERT((v.Oyzx(c) == eagine::math::tvec<T,4,V>(c, v.y(), v.z(), v.x())));
BOOST_ASSERT((v.Oyzy(c) == eagine::math::tvec<T,4,V>(c, v.y(), v.z(), v.y())));
BOOST_ASSERT((v.Oyzz(c) == eagine::math::tvec<T,4,V>(c, v.y(), v.z(), v.z())));
BOOST_ASSERT((v.Oyzw(c) == eagine::math::tvec<T,4,V>(c, v.y(), v.z(), v.w())));
BOOST_ASSERT((v.OywO(c) == eagine::math::tvec<T,4,V>(c, v.y(), v.w(), c)));
BOOST_ASSERT((v.Oywx(c) == eagine::math::tvec<T,4,V>(c, v.y(), v.w(), v.x())));
BOOST_ASSERT((v.Oywy(c) == eagine::math::tvec<T,4,V>(c, v.y(), v.w(), v.y())));
BOOST_ASSERT((v.Oywz(c) == eagine::math::tvec<T,4,V>(c, v.y(), v.w(), v.z())));
BOOST_ASSERT((v.Oyww(c) == eagine::math::tvec<T,4,V>(c, v.y(), v.w(), v.w())));
BOOST_ASSERT((v.OzOO(c) == eagine::math::tvec<T,4,V>(c, v.z(), c, c)));
BOOST_ASSERT((v.OzOx(c) == eagine::math::tvec<T,4,V>(c, v.z(), c, v.x())));
BOOST_ASSERT((v.OzOy(c) == eagine::math::tvec<T,4,V>(c, v.z(), c, v.y())));
BOOST_ASSERT((v.OzOz(c) == eagine::math::tvec<T,4,V>(c, v.z(), c, v.z())));
BOOST_ASSERT((v.OzOw(c) == eagine::math::tvec<T,4,V>(c, v.z(), c, v.w())));
BOOST_ASSERT((v.OzxO(c) == eagine::math::tvec<T,4,V>(c, v.z(), v.x(), c)));
BOOST_ASSERT((v.Ozxx(c) == eagine::math::tvec<T,4,V>(c, v.z(), v.x(), v.x())));
BOOST_ASSERT((v.Ozxy(c) == eagine::math::tvec<T,4,V>(c, v.z(), v.x(), v.y())));
BOOST_ASSERT((v.Ozxz(c) == eagine::math::tvec<T,4,V>(c, v.z(), v.x(), v.z())));
BOOST_ASSERT((v.Ozxw(c) == eagine::math::tvec<T,4,V>(c, v.z(), v.x(), v.w())));
BOOST_ASSERT((v.OzyO(c) == eagine::math::tvec<T,4,V>(c, v.z(), v.y(), c)));
BOOST_ASSERT((v.Ozyx(c) == eagine::math::tvec<T,4,V>(c, v.z(), v.y(), v.x())));
BOOST_ASSERT((v.Ozyy(c) == eagine::math::tvec<T,4,V>(c, v.z(), v.y(), v.y())));
BOOST_ASSERT((v.Ozyz(c) == eagine::math::tvec<T,4,V>(c, v.z(), v.y(), v.z())));
BOOST_ASSERT((v.Ozyw(c) == eagine::math::tvec<T,4,V>(c, v.z(), v.y(), v.w())));
BOOST_ASSERT((v.OzzO(c) == eagine::math::tvec<T,4,V>(c, v.z(), v.z(), c)));
BOOST_ASSERT((v.Ozzx(c) == eagine::math::tvec<T,4,V>(c, v.z(), v.z(), v.x())));
BOOST_ASSERT((v.Ozzy(c) == eagine::math::tvec<T,4,V>(c, v.z(), v.z(), v.y())));
BOOST_ASSERT((v.Ozzz(c) == eagine::math::tvec<T,4,V>(c, v.z(), v.z(), v.z())));
BOOST_ASSERT((v.Ozzw(c) == eagine::math::tvec<T,4,V>(c, v.z(), v.z(), v.w())));
BOOST_ASSERT((v.OzwO(c) == eagine::math::tvec<T,4,V>(c, v.z(), v.w(), c)));
BOOST_ASSERT((v.Ozwx(c) == eagine::math::tvec<T,4,V>(c, v.z(), v.w(), v.x())));
BOOST_ASSERT((v.Ozwy(c) == eagine::math::tvec<T,4,V>(c, v.z(), v.w(), v.y())));
BOOST_ASSERT((v.Ozwz(c) == eagine::math::tvec<T,4,V>(c, v.z(), v.w(), v.z())));
BOOST_ASSERT((v.Ozww(c) == eagine::math::tvec<T,4,V>(c, v.z(), v.w(), v.w())));
BOOST_ASSERT((v.OwOO(c) == eagine::math::tvec<T,4,V>(c, v.w(), c, c)));
BOOST_ASSERT((v.OwOx(c) == eagine::math::tvec<T,4,V>(c, v.w(), c, v.x())));
BOOST_ASSERT((v.OwOy(c) == eagine::math::tvec<T,4,V>(c, v.w(), c, v.y())));
BOOST_ASSERT((v.OwOz(c) == eagine::math::tvec<T,4,V>(c, v.w(), c, v.z())));
BOOST_ASSERT((v.OwOw(c) == eagine::math::tvec<T,4,V>(c, v.w(), c, v.w())));
BOOST_ASSERT((v.OwxO(c) == eagine::math::tvec<T,4,V>(c, v.w(), v.x(), c)));
BOOST_ASSERT((v.Owxx(c) == eagine::math::tvec<T,4,V>(c, v.w(), v.x(), v.x())));
BOOST_ASSERT((v.Owxy(c) == eagine::math::tvec<T,4,V>(c, v.w(), v.x(), v.y())));
BOOST_ASSERT((v.Owxz(c) == eagine::math::tvec<T,4,V>(c, v.w(), v.x(), v.z())));
BOOST_ASSERT((v.Owxw(c) == eagine::math::tvec<T,4,V>(c, v.w(), v.x(), v.w())));
BOOST_ASSERT((v.OwyO(c) == eagine::math::tvec<T,4,V>(c, v.w(), v.y(), c)));
BOOST_ASSERT((v.Owyx(c) == eagine::math::tvec<T,4,V>(c, v.w(), v.y(), v.x())));
BOOST_ASSERT((v.Owyy(c) == eagine::math::tvec<T,4,V>(c, v.w(), v.y(), v.y())));
BOOST_ASSERT((v.Owyz(c) == eagine::math::tvec<T,4,V>(c, v.w(), v.y(), v.z())));
BOOST_ASSERT((v.Owyw(c) == eagine::math::tvec<T,4,V>(c, v.w(), v.y(), v.w())));
BOOST_ASSERT((v.OwzO(c) == eagine::math::tvec<T,4,V>(c, v.w(), v.z(), c)));
BOOST_ASSERT((v.Owzx(c) == eagine::math::tvec<T,4,V>(c, v.w(), v.z(), v.x())));
BOOST_ASSERT((v.Owzy(c) == eagine::math::tvec<T,4,V>(c, v.w(), v.z(), v.y())));
BOOST_ASSERT((v.Owzz(c) == eagine::math::tvec<T,4,V>(c, v.w(), v.z(), v.z())));
BOOST_ASSERT((v.Owzw(c) == eagine::math::tvec<T,4,V>(c, v.w(), v.z(), v.w())));
BOOST_ASSERT((v.OwwO(c) == eagine::math::tvec<T,4,V>(c, v.w(), v.w(), c)));
BOOST_ASSERT((v.Owwx(c) == eagine::math::tvec<T,4,V>(c, v.w(), v.w(), v.x())));
BOOST_ASSERT((v.Owwy(c) == eagine::math::tvec<T,4,V>(c, v.w(), v.w(), v.y())));
BOOST_ASSERT((v.Owwz(c) == eagine::math::tvec<T,4,V>(c, v.w(), v.w(), v.z())));
BOOST_ASSERT((v.Owww(c) == eagine::math::tvec<T,4,V>(c, v.w(), v.w(), v.w())));
BOOST_ASSERT((v.xOOO(c) == eagine::math::tvec<T,4,V>(v.x(), c, c, c)));
BOOST_ASSERT((v.xOOx(c) == eagine::math::tvec<T,4,V>(v.x(), c, c, v.x())));
BOOST_ASSERT((v.xOOy(c) == eagine::math::tvec<T,4,V>(v.x(), c, c, v.y())));
BOOST_ASSERT((v.xOOz(c) == eagine::math::tvec<T,4,V>(v.x(), c, c, v.z())));
BOOST_ASSERT((v.xOOw(c) == eagine::math::tvec<T,4,V>(v.x(), c, c, v.w())));
BOOST_ASSERT((v.xOxO(c) == eagine::math::tvec<T,4,V>(v.x(), c, v.x(), c)));
BOOST_ASSERT((v.xOxx(c) == eagine::math::tvec<T,4,V>(v.x(), c, v.x(), v.x())));
BOOST_ASSERT((v.xOxy(c) == eagine::math::tvec<T,4,V>(v.x(), c, v.x(), v.y())));
BOOST_ASSERT((v.xOxz(c) == eagine::math::tvec<T,4,V>(v.x(), c, v.x(), v.z())));
BOOST_ASSERT((v.xOxw(c) == eagine::math::tvec<T,4,V>(v.x(), c, v.x(), v.w())));
BOOST_ASSERT((v.xOyO(c) == eagine::math::tvec<T,4,V>(v.x(), c, v.y(), c)));
BOOST_ASSERT((v.xOyx(c) == eagine::math::tvec<T,4,V>(v.x(), c, v.y(), v.x())));
BOOST_ASSERT((v.xOyy(c) == eagine::math::tvec<T,4,V>(v.x(), c, v.y(), v.y())));
BOOST_ASSERT((v.xOyz(c) == eagine::math::tvec<T,4,V>(v.x(), c, v.y(), v.z())));
BOOST_ASSERT((v.xOyw(c) == eagine::math::tvec<T,4,V>(v.x(), c, v.y(), v.w())));
BOOST_ASSERT((v.xOzO(c) == eagine::math::tvec<T,4,V>(v.x(), c, v.z(), c)));
BOOST_ASSERT((v.xOzx(c) == eagine::math::tvec<T,4,V>(v.x(), c, v.z(), v.x())));
BOOST_ASSERT((v.xOzy(c) == eagine::math::tvec<T,4,V>(v.x(), c, v.z(), v.y())));
BOOST_ASSERT((v.xOzz(c) == eagine::math::tvec<T,4,V>(v.x(), c, v.z(), v.z())));
BOOST_ASSERT((v.xOzw(c) == eagine::math::tvec<T,4,V>(v.x(), c, v.z(), v.w())));
BOOST_ASSERT((v.xOwO(c) == eagine::math::tvec<T,4,V>(v.x(), c, v.w(), c)));
BOOST_ASSERT((v.xOwx(c) == eagine::math::tvec<T,4,V>(v.x(), c, v.w(), v.x())));
BOOST_ASSERT((v.xOwy(c) == eagine::math::tvec<T,4,V>(v.x(), c, v.w(), v.y())));
BOOST_ASSERT((v.xOwz(c) == eagine::math::tvec<T,4,V>(v.x(), c, v.w(), v.z())));
BOOST_ASSERT((v.xOww(c) == eagine::math::tvec<T,4,V>(v.x(), c, v.w(), v.w())));
BOOST_ASSERT((v.xxOO(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), c, c)));
BOOST_ASSERT((v.xxOx(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), c, v.x())));
BOOST_ASSERT((v.xxOy(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), c, v.y())));
BOOST_ASSERT((v.xxOz(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), c, v.z())));
BOOST_ASSERT((v.xxOw(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), c, v.w())));
BOOST_ASSERT((v.xxxO(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), v.x(), c)));
BOOST_ASSERT((v.xxxx(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), v.x(), v.x())));
BOOST_ASSERT((v.xxxy(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), v.x(), v.y())));
BOOST_ASSERT((v.xxxz(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), v.x(), v.z())));
BOOST_ASSERT((v.xxxw(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), v.x(), v.w())));
BOOST_ASSERT((v.xxyO(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), v.y(), c)));
BOOST_ASSERT((v.xxyx(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), v.y(), v.x())));
BOOST_ASSERT((v.xxyy(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), v.y(), v.y())));
BOOST_ASSERT((v.xxyz(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), v.y(), v.z())));
BOOST_ASSERT((v.xxyw(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), v.y(), v.w())));
BOOST_ASSERT((v.xxzO(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), v.z(), c)));
BOOST_ASSERT((v.xxzx(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), v.z(), v.x())));
BOOST_ASSERT((v.xxzy(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), v.z(), v.y())));
BOOST_ASSERT((v.xxzz(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), v.z(), v.z())));
BOOST_ASSERT((v.xxzw(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), v.z(), v.w())));
BOOST_ASSERT((v.xxwO(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), v.w(), c)));
BOOST_ASSERT((v.xxwx(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), v.w(), v.x())));
BOOST_ASSERT((v.xxwy(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), v.w(), v.y())));
BOOST_ASSERT((v.xxwz(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), v.w(), v.z())));
BOOST_ASSERT((v.xxww(c) == eagine::math::tvec<T,4,V>(v.x(), v.x(), v.w(), v.w())));
BOOST_ASSERT((v.xyOO(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), c, c)));
BOOST_ASSERT((v.xyOx(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), c, v.x())));
BOOST_ASSERT((v.xyOy(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), c, v.y())));
BOOST_ASSERT((v.xyOz(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), c, v.z())));
BOOST_ASSERT((v.xyOw(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), c, v.w())));
BOOST_ASSERT((v.xyxO(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), v.x(), c)));
BOOST_ASSERT((v.xyxx(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), v.x(), v.x())));
BOOST_ASSERT((v.xyxy(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), v.x(), v.y())));
BOOST_ASSERT((v.xyxz(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), v.x(), v.z())));
BOOST_ASSERT((v.xyxw(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), v.x(), v.w())));
BOOST_ASSERT((v.xyyO(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), v.y(), c)));
BOOST_ASSERT((v.xyyx(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), v.y(), v.x())));
BOOST_ASSERT((v.xyyy(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), v.y(), v.y())));
BOOST_ASSERT((v.xyyz(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), v.y(), v.z())));
BOOST_ASSERT((v.xyyw(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), v.y(), v.w())));
BOOST_ASSERT((v.xyzO(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), v.z(), c)));
BOOST_ASSERT((v.xyzx(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), v.z(), v.x())));
BOOST_ASSERT((v.xyzy(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), v.z(), v.y())));
BOOST_ASSERT((v.xyzz(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), v.z(), v.z())));
BOOST_ASSERT((v.xyzw(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), v.z(), v.w())));
BOOST_ASSERT((v.xywO(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), v.w(), c)));
BOOST_ASSERT((v.xywx(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), v.w(), v.x())));
BOOST_ASSERT((v.xywy(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), v.w(), v.y())));
BOOST_ASSERT((v.xywz(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), v.w(), v.z())));
BOOST_ASSERT((v.xyww(c) == eagine::math::tvec<T,4,V>(v.x(), v.y(), v.w(), v.w())));
BOOST_ASSERT((v.xzOO(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), c, c)));
BOOST_ASSERT((v.xzOx(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), c, v.x())));
BOOST_ASSERT((v.xzOy(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), c, v.y())));
BOOST_ASSERT((v.xzOz(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), c, v.z())));
BOOST_ASSERT((v.xzOw(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), c, v.w())));
BOOST_ASSERT((v.xzxO(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), v.x(), c)));
BOOST_ASSERT((v.xzxx(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), v.x(), v.x())));
BOOST_ASSERT((v.xzxy(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), v.x(), v.y())));
BOOST_ASSERT((v.xzxz(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), v.x(), v.z())));
BOOST_ASSERT((v.xzxw(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), v.x(), v.w())));
BOOST_ASSERT((v.xzyO(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), v.y(), c)));
BOOST_ASSERT((v.xzyx(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), v.y(), v.x())));
BOOST_ASSERT((v.xzyy(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), v.y(), v.y())));
BOOST_ASSERT((v.xzyz(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), v.y(), v.z())));
BOOST_ASSERT((v.xzyw(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), v.y(), v.w())));
BOOST_ASSERT((v.xzzO(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), v.z(), c)));
BOOST_ASSERT((v.xzzx(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), v.z(), v.x())));
BOOST_ASSERT((v.xzzy(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), v.z(), v.y())));
BOOST_ASSERT((v.xzzz(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), v.z(), v.z())));
BOOST_ASSERT((v.xzzw(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), v.z(), v.w())));
BOOST_ASSERT((v.xzwO(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), v.w(), c)));
BOOST_ASSERT((v.xzwx(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), v.w(), v.x())));
BOOST_ASSERT((v.xzwy(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), v.w(), v.y())));
BOOST_ASSERT((v.xzwz(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), v.w(), v.z())));
BOOST_ASSERT((v.xzww(c) == eagine::math::tvec<T,4,V>(v.x(), v.z(), v.w(), v.w())));
BOOST_ASSERT((v.xwOO(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), c, c)));
BOOST_ASSERT((v.xwOx(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), c, v.x())));
BOOST_ASSERT((v.xwOy(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), c, v.y())));
BOOST_ASSERT((v.xwOz(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), c, v.z())));
BOOST_ASSERT((v.xwOw(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), c, v.w())));
BOOST_ASSERT((v.xwxO(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), v.x(), c)));
BOOST_ASSERT((v.xwxx(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), v.x(), v.x())));
BOOST_ASSERT((v.xwxy(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), v.x(), v.y())));
BOOST_ASSERT((v.xwxz(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), v.x(), v.z())));
BOOST_ASSERT((v.xwxw(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), v.x(), v.w())));
BOOST_ASSERT((v.xwyO(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), v.y(), c)));
BOOST_ASSERT((v.xwyx(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), v.y(), v.x())));
BOOST_ASSERT((v.xwyy(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), v.y(), v.y())));
BOOST_ASSERT((v.xwyz(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), v.y(), v.z())));
BOOST_ASSERT((v.xwyw(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), v.y(), v.w())));
BOOST_ASSERT((v.xwzO(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), v.z(), c)));
BOOST_ASSERT((v.xwzx(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), v.z(), v.x())));
BOOST_ASSERT((v.xwzy(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), v.z(), v.y())));
BOOST_ASSERT((v.xwzz(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), v.z(), v.z())));
BOOST_ASSERT((v.xwzw(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), v.z(), v.w())));
BOOST_ASSERT((v.xwwO(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), v.w(), c)));
BOOST_ASSERT((v.xwwx(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), v.w(), v.x())));
BOOST_ASSERT((v.xwwy(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), v.w(), v.y())));
BOOST_ASSERT((v.xwwz(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), v.w(), v.z())));
BOOST_ASSERT((v.xwww(c) == eagine::math::tvec<T,4,V>(v.x(), v.w(), v.w(), v.w())));
BOOST_ASSERT((v.yOOO(c) == eagine::math::tvec<T,4,V>(v.y(), c, c, c)));
BOOST_ASSERT((v.yOOx(c) == eagine::math::tvec<T,4,V>(v.y(), c, c, v.x())));
BOOST_ASSERT((v.yOOy(c) == eagine::math::tvec<T,4,V>(v.y(), c, c, v.y())));
BOOST_ASSERT((v.yOOz(c) == eagine::math::tvec<T,4,V>(v.y(), c, c, v.z())));
BOOST_ASSERT((v.yOOw(c) == eagine::math::tvec<T,4,V>(v.y(), c, c, v.w())));
BOOST_ASSERT((v.yOxO(c) == eagine::math::tvec<T,4,V>(v.y(), c, v.x(), c)));
BOOST_ASSERT((v.yOxx(c) == eagine::math::tvec<T,4,V>(v.y(), c, v.x(), v.x())));
BOOST_ASSERT((v.yOxy(c) == eagine::math::tvec<T,4,V>(v.y(), c, v.x(), v.y())));
BOOST_ASSERT((v.yOxz(c) == eagine::math::tvec<T,4,V>(v.y(), c, v.x(), v.z())));
BOOST_ASSERT((v.yOxw(c) == eagine::math::tvec<T,4,V>(v.y(), c, v.x(), v.w())));
BOOST_ASSERT((v.yOyO(c) == eagine::math::tvec<T,4,V>(v.y(), c, v.y(), c)));
BOOST_ASSERT((v.yOyx(c) == eagine::math::tvec<T,4,V>(v.y(), c, v.y(), v.x())));
BOOST_ASSERT((v.yOyy(c) == eagine::math::tvec<T,4,V>(v.y(), c, v.y(), v.y())));
BOOST_ASSERT((v.yOyz(c) == eagine::math::tvec<T,4,V>(v.y(), c, v.y(), v.z())));
BOOST_ASSERT((v.yOyw(c) == eagine::math::tvec<T,4,V>(v.y(), c, v.y(), v.w())));
BOOST_ASSERT((v.yOzO(c) == eagine::math::tvec<T,4,V>(v.y(), c, v.z(), c)));
BOOST_ASSERT((v.yOzx(c) == eagine::math::tvec<T,4,V>(v.y(), c, v.z(), v.x())));
BOOST_ASSERT((v.yOzy(c) == eagine::math::tvec<T,4,V>(v.y(), c, v.z(), v.y())));
BOOST_ASSERT((v.yOzz(c) == eagine::math::tvec<T,4,V>(v.y(), c, v.z(), v.z())));
BOOST_ASSERT((v.yOzw(c) == eagine::math::tvec<T,4,V>(v.y(), c, v.z(), v.w())));
BOOST_ASSERT((v.yOwO(c) == eagine::math::tvec<T,4,V>(v.y(), c, v.w(), c)));
BOOST_ASSERT((v.yOwx(c) == eagine::math::tvec<T,4,V>(v.y(), c, v.w(), v.x())));
BOOST_ASSERT((v.yOwy(c) == eagine::math::tvec<T,4,V>(v.y(), c, v.w(), v.y())));
BOOST_ASSERT((v.yOwz(c) == eagine::math::tvec<T,4,V>(v.y(), c, v.w(), v.z())));
BOOST_ASSERT((v.yOww(c) == eagine::math::tvec<T,4,V>(v.y(), c, v.w(), v.w())));
BOOST_ASSERT((v.yxOO(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), c, c)));
BOOST_ASSERT((v.yxOx(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), c, v.x())));
BOOST_ASSERT((v.yxOy(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), c, v.y())));
BOOST_ASSERT((v.yxOz(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), c, v.z())));
BOOST_ASSERT((v.yxOw(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), c, v.w())));
BOOST_ASSERT((v.yxxO(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), v.x(), c)));
BOOST_ASSERT((v.yxxx(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), v.x(), v.x())));
BOOST_ASSERT((v.yxxy(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), v.x(), v.y())));
BOOST_ASSERT((v.yxxz(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), v.x(), v.z())));
BOOST_ASSERT((v.yxxw(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), v.x(), v.w())));
BOOST_ASSERT((v.yxyO(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), v.y(), c)));
BOOST_ASSERT((v.yxyx(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), v.y(), v.x())));
BOOST_ASSERT((v.yxyy(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), v.y(), v.y())));
BOOST_ASSERT((v.yxyz(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), v.y(), v.z())));
BOOST_ASSERT((v.yxyw(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), v.y(), v.w())));
BOOST_ASSERT((v.yxzO(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), v.z(), c)));
BOOST_ASSERT((v.yxzx(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), v.z(), v.x())));
BOOST_ASSERT((v.yxzy(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), v.z(), v.y())));
BOOST_ASSERT((v.yxzz(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), v.z(), v.z())));
BOOST_ASSERT((v.yxzw(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), v.z(), v.w())));
BOOST_ASSERT((v.yxwO(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), v.w(), c)));
BOOST_ASSERT((v.yxwx(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), v.w(), v.x())));
BOOST_ASSERT((v.yxwy(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), v.w(), v.y())));
BOOST_ASSERT((v.yxwz(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), v.w(), v.z())));
BOOST_ASSERT((v.yxww(c) == eagine::math::tvec<T,4,V>(v.y(), v.x(), v.w(), v.w())));
BOOST_ASSERT((v.yyOO(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), c, c)));
BOOST_ASSERT((v.yyOx(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), c, v.x())));
BOOST_ASSERT((v.yyOy(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), c, v.y())));
BOOST_ASSERT((v.yyOz(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), c, v.z())));
BOOST_ASSERT((v.yyOw(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), c, v.w())));
BOOST_ASSERT((v.yyxO(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), v.x(), c)));
BOOST_ASSERT((v.yyxx(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), v.x(), v.x())));
BOOST_ASSERT((v.yyxy(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), v.x(), v.y())));
BOOST_ASSERT((v.yyxz(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), v.x(), v.z())));
BOOST_ASSERT((v.yyxw(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), v.x(), v.w())));
BOOST_ASSERT((v.yyyO(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), v.y(), c)));
BOOST_ASSERT((v.yyyx(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), v.y(), v.x())));
BOOST_ASSERT((v.yyyy(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), v.y(), v.y())));
BOOST_ASSERT((v.yyyz(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), v.y(), v.z())));
BOOST_ASSERT((v.yyyw(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), v.y(), v.w())));
BOOST_ASSERT((v.yyzO(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), v.z(), c)));
BOOST_ASSERT((v.yyzx(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), v.z(), v.x())));
BOOST_ASSERT((v.yyzy(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), v.z(), v.y())));
BOOST_ASSERT((v.yyzz(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), v.z(), v.z())));
BOOST_ASSERT((v.yyzw(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), v.z(), v.w())));
BOOST_ASSERT((v.yywO(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), v.w(), c)));
BOOST_ASSERT((v.yywx(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), v.w(), v.x())));
BOOST_ASSERT((v.yywy(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), v.w(), v.y())));
BOOST_ASSERT((v.yywz(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), v.w(), v.z())));
BOOST_ASSERT((v.yyww(c) == eagine::math::tvec<T,4,V>(v.y(), v.y(), v.w(), v.w())));
BOOST_ASSERT((v.yzOO(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), c, c)));
BOOST_ASSERT((v.yzOx(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), c, v.x())));
BOOST_ASSERT((v.yzOy(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), c, v.y())));
BOOST_ASSERT((v.yzOz(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), c, v.z())));
BOOST_ASSERT((v.yzOw(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), c, v.w())));
BOOST_ASSERT((v.yzxO(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), v.x(), c)));
BOOST_ASSERT((v.yzxx(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), v.x(), v.x())));
BOOST_ASSERT((v.yzxy(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), v.x(), v.y())));
BOOST_ASSERT((v.yzxz(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), v.x(), v.z())));
BOOST_ASSERT((v.yzxw(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), v.x(), v.w())));
BOOST_ASSERT((v.yzyO(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), v.y(), c)));
BOOST_ASSERT((v.yzyx(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), v.y(), v.x())));
BOOST_ASSERT((v.yzyy(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), v.y(), v.y())));
BOOST_ASSERT((v.yzyz(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), v.y(), v.z())));
BOOST_ASSERT((v.yzyw(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), v.y(), v.w())));
BOOST_ASSERT((v.yzzO(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), v.z(), c)));
BOOST_ASSERT((v.yzzx(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), v.z(), v.x())));
BOOST_ASSERT((v.yzzy(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), v.z(), v.y())));
BOOST_ASSERT((v.yzzz(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), v.z(), v.z())));
BOOST_ASSERT((v.yzzw(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), v.z(), v.w())));
BOOST_ASSERT((v.yzwO(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), v.w(), c)));
BOOST_ASSERT((v.yzwx(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), v.w(), v.x())));
BOOST_ASSERT((v.yzwy(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), v.w(), v.y())));
BOOST_ASSERT((v.yzwz(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), v.w(), v.z())));
BOOST_ASSERT((v.yzww(c) == eagine::math::tvec<T,4,V>(v.y(), v.z(), v.w(), v.w())));
BOOST_ASSERT((v.ywOO(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), c, c)));
BOOST_ASSERT((v.ywOx(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), c, v.x())));
BOOST_ASSERT((v.ywOy(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), c, v.y())));
BOOST_ASSERT((v.ywOz(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), c, v.z())));
BOOST_ASSERT((v.ywOw(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), c, v.w())));
BOOST_ASSERT((v.ywxO(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), v.x(), c)));
BOOST_ASSERT((v.ywxx(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), v.x(), v.x())));
BOOST_ASSERT((v.ywxy(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), v.x(), v.y())));
BOOST_ASSERT((v.ywxz(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), v.x(), v.z())));
BOOST_ASSERT((v.ywxw(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), v.x(), v.w())));
BOOST_ASSERT((v.ywyO(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), v.y(), c)));
BOOST_ASSERT((v.ywyx(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), v.y(), v.x())));
BOOST_ASSERT((v.ywyy(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), v.y(), v.y())));
BOOST_ASSERT((v.ywyz(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), v.y(), v.z())));
BOOST_ASSERT((v.ywyw(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), v.y(), v.w())));
BOOST_ASSERT((v.ywzO(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), v.z(), c)));
BOOST_ASSERT((v.ywzx(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), v.z(), v.x())));
BOOST_ASSERT((v.ywzy(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), v.z(), v.y())));
BOOST_ASSERT((v.ywzz(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), v.z(), v.z())));
BOOST_ASSERT((v.ywzw(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), v.z(), v.w())));
BOOST_ASSERT((v.ywwO(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), v.w(), c)));
BOOST_ASSERT((v.ywwx(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), v.w(), v.x())));
BOOST_ASSERT((v.ywwy(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), v.w(), v.y())));
BOOST_ASSERT((v.ywwz(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), v.w(), v.z())));
BOOST_ASSERT((v.ywww(c) == eagine::math::tvec<T,4,V>(v.y(), v.w(), v.w(), v.w())));
BOOST_ASSERT((v.zOOO(c) == eagine::math::tvec<T,4,V>(v.z(), c, c, c)));
BOOST_ASSERT((v.zOOx(c) == eagine::math::tvec<T,4,V>(v.z(), c, c, v.x())));
BOOST_ASSERT((v.zOOy(c) == eagine::math::tvec<T,4,V>(v.z(), c, c, v.y())));
BOOST_ASSERT((v.zOOz(c) == eagine::math::tvec<T,4,V>(v.z(), c, c, v.z())));
BOOST_ASSERT((v.zOOw(c) == eagine::math::tvec<T,4,V>(v.z(), c, c, v.w())));
BOOST_ASSERT((v.zOxO(c) == eagine::math::tvec<T,4,V>(v.z(), c, v.x(), c)));
BOOST_ASSERT((v.zOxx(c) == eagine::math::tvec<T,4,V>(v.z(), c, v.x(), v.x())));
BOOST_ASSERT((v.zOxy(c) == eagine::math::tvec<T,4,V>(v.z(), c, v.x(), v.y())));
BOOST_ASSERT((v.zOxz(c) == eagine::math::tvec<T,4,V>(v.z(), c, v.x(), v.z())));
BOOST_ASSERT((v.zOxw(c) == eagine::math::tvec<T,4,V>(v.z(), c, v.x(), v.w())));
BOOST_ASSERT((v.zOyO(c) == eagine::math::tvec<T,4,V>(v.z(), c, v.y(), c)));
BOOST_ASSERT((v.zOyx(c) == eagine::math::tvec<T,4,V>(v.z(), c, v.y(), v.x())));
BOOST_ASSERT((v.zOyy(c) == eagine::math::tvec<T,4,V>(v.z(), c, v.y(), v.y())));
BOOST_ASSERT((v.zOyz(c) == eagine::math::tvec<T,4,V>(v.z(), c, v.y(), v.z())));
BOOST_ASSERT((v.zOyw(c) == eagine::math::tvec<T,4,V>(v.z(), c, v.y(), v.w())));
BOOST_ASSERT((v.zOzO(c) == eagine::math::tvec<T,4,V>(v.z(), c, v.z(), c)));
BOOST_ASSERT((v.zOzx(c) == eagine::math::tvec<T,4,V>(v.z(), c, v.z(), v.x())));
BOOST_ASSERT((v.zOzy(c) == eagine::math::tvec<T,4,V>(v.z(), c, v.z(), v.y())));
BOOST_ASSERT((v.zOzz(c) == eagine::math::tvec<T,4,V>(v.z(), c, v.z(), v.z())));
BOOST_ASSERT((v.zOzw(c) == eagine::math::tvec<T,4,V>(v.z(), c, v.z(), v.w())));
BOOST_ASSERT((v.zOwO(c) == eagine::math::tvec<T,4,V>(v.z(), c, v.w(), c)));
BOOST_ASSERT((v.zOwx(c) == eagine::math::tvec<T,4,V>(v.z(), c, v.w(), v.x())));
BOOST_ASSERT((v.zOwy(c) == eagine::math::tvec<T,4,V>(v.z(), c, v.w(), v.y())));
BOOST_ASSERT((v.zOwz(c) == eagine::math::tvec<T,4,V>(v.z(), c, v.w(), v.z())));
BOOST_ASSERT((v.zOww(c) == eagine::math::tvec<T,4,V>(v.z(), c, v.w(), v.w())));
BOOST_ASSERT((v.zxOO(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), c, c)));
BOOST_ASSERT((v.zxOx(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), c, v.x())));
BOOST_ASSERT((v.zxOy(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), c, v.y())));
BOOST_ASSERT((v.zxOz(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), c, v.z())));
BOOST_ASSERT((v.zxOw(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), c, v.w())));
BOOST_ASSERT((v.zxxO(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), v.x(), c)));
BOOST_ASSERT((v.zxxx(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), v.x(), v.x())));
BOOST_ASSERT((v.zxxy(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), v.x(), v.y())));
BOOST_ASSERT((v.zxxz(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), v.x(), v.z())));
BOOST_ASSERT((v.zxxw(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), v.x(), v.w())));
BOOST_ASSERT((v.zxyO(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), v.y(), c)));
BOOST_ASSERT((v.zxyx(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), v.y(), v.x())));
BOOST_ASSERT((v.zxyy(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), v.y(), v.y())));
BOOST_ASSERT((v.zxyz(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), v.y(), v.z())));
BOOST_ASSERT((v.zxyw(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), v.y(), v.w())));
BOOST_ASSERT((v.zxzO(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), v.z(), c)));
BOOST_ASSERT((v.zxzx(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), v.z(), v.x())));
BOOST_ASSERT((v.zxzy(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), v.z(), v.y())));
BOOST_ASSERT((v.zxzz(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), v.z(), v.z())));
BOOST_ASSERT((v.zxzw(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), v.z(), v.w())));
BOOST_ASSERT((v.zxwO(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), v.w(), c)));
BOOST_ASSERT((v.zxwx(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), v.w(), v.x())));
BOOST_ASSERT((v.zxwy(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), v.w(), v.y())));
BOOST_ASSERT((v.zxwz(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), v.w(), v.z())));
BOOST_ASSERT((v.zxww(c) == eagine::math::tvec<T,4,V>(v.z(), v.x(), v.w(), v.w())));
BOOST_ASSERT((v.zyOO(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), c, c)));
BOOST_ASSERT((v.zyOx(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), c, v.x())));
BOOST_ASSERT((v.zyOy(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), c, v.y())));
BOOST_ASSERT((v.zyOz(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), c, v.z())));
BOOST_ASSERT((v.zyOw(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), c, v.w())));
BOOST_ASSERT((v.zyxO(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), v.x(), c)));
BOOST_ASSERT((v.zyxx(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), v.x(), v.x())));
BOOST_ASSERT((v.zyxy(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), v.x(), v.y())));
BOOST_ASSERT((v.zyxz(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), v.x(), v.z())));
BOOST_ASSERT((v.zyxw(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), v.x(), v.w())));
BOOST_ASSERT((v.zyyO(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), v.y(), c)));
BOOST_ASSERT((v.zyyx(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), v.y(), v.x())));
BOOST_ASSERT((v.zyyy(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), v.y(), v.y())));
BOOST_ASSERT((v.zyyz(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), v.y(), v.z())));
BOOST_ASSERT((v.zyyw(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), v.y(), v.w())));
BOOST_ASSERT((v.zyzO(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), v.z(), c)));
BOOST_ASSERT((v.zyzx(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), v.z(), v.x())));
BOOST_ASSERT((v.zyzy(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), v.z(), v.y())));
BOOST_ASSERT((v.zyzz(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), v.z(), v.z())));
BOOST_ASSERT((v.zyzw(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), v.z(), v.w())));
BOOST_ASSERT((v.zywO(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), v.w(), c)));
BOOST_ASSERT((v.zywx(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), v.w(), v.x())));
BOOST_ASSERT((v.zywy(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), v.w(), v.y())));
BOOST_ASSERT((v.zywz(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), v.w(), v.z())));
BOOST_ASSERT((v.zyww(c) == eagine::math::tvec<T,4,V>(v.z(), v.y(), v.w(), v.w())));
BOOST_ASSERT((v.zzOO(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), c, c)));
BOOST_ASSERT((v.zzOx(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), c, v.x())));
BOOST_ASSERT((v.zzOy(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), c, v.y())));
BOOST_ASSERT((v.zzOz(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), c, v.z())));
BOOST_ASSERT((v.zzOw(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), c, v.w())));
BOOST_ASSERT((v.zzxO(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), v.x(), c)));
BOOST_ASSERT((v.zzxx(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), v.x(), v.x())));
BOOST_ASSERT((v.zzxy(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), v.x(), v.y())));
BOOST_ASSERT((v.zzxz(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), v.x(), v.z())));
BOOST_ASSERT((v.zzxw(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), v.x(), v.w())));
BOOST_ASSERT((v.zzyO(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), v.y(), c)));
BOOST_ASSERT((v.zzyx(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), v.y(), v.x())));
BOOST_ASSERT((v.zzyy(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), v.y(), v.y())));
BOOST_ASSERT((v.zzyz(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), v.y(), v.z())));
BOOST_ASSERT((v.zzyw(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), v.y(), v.w())));
BOOST_ASSERT((v.zzzO(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), v.z(), c)));
BOOST_ASSERT((v.zzzx(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), v.z(), v.x())));
BOOST_ASSERT((v.zzzy(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), v.z(), v.y())));
BOOST_ASSERT((v.zzzz(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), v.z(), v.z())));
BOOST_ASSERT((v.zzzw(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), v.z(), v.w())));
BOOST_ASSERT((v.zzwO(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), v.w(), c)));
BOOST_ASSERT((v.zzwx(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), v.w(), v.x())));
BOOST_ASSERT((v.zzwy(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), v.w(), v.y())));
BOOST_ASSERT((v.zzwz(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), v.w(), v.z())));
BOOST_ASSERT((v.zzww(c) == eagine::math::tvec<T,4,V>(v.z(), v.z(), v.w(), v.w())));
BOOST_ASSERT((v.zwOO(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), c, c)));
BOOST_ASSERT((v.zwOx(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), c, v.x())));
BOOST_ASSERT((v.zwOy(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), c, v.y())));
BOOST_ASSERT((v.zwOz(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), c, v.z())));
BOOST_ASSERT((v.zwOw(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), c, v.w())));
BOOST_ASSERT((v.zwxO(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), v.x(), c)));
BOOST_ASSERT((v.zwxx(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), v.x(), v.x())));
BOOST_ASSERT((v.zwxy(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), v.x(), v.y())));
BOOST_ASSERT((v.zwxz(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), v.x(), v.z())));
BOOST_ASSERT((v.zwxw(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), v.x(), v.w())));
BOOST_ASSERT((v.zwyO(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), v.y(), c)));
BOOST_ASSERT((v.zwyx(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), v.y(), v.x())));
BOOST_ASSERT((v.zwyy(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), v.y(), v.y())));
BOOST_ASSERT((v.zwyz(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), v.y(), v.z())));
BOOST_ASSERT((v.zwyw(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), v.y(), v.w())));
BOOST_ASSERT((v.zwzO(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), v.z(), c)));
BOOST_ASSERT((v.zwzx(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), v.z(), v.x())));
BOOST_ASSERT((v.zwzy(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), v.z(), v.y())));
BOOST_ASSERT((v.zwzz(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), v.z(), v.z())));
BOOST_ASSERT((v.zwzw(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), v.z(), v.w())));
BOOST_ASSERT((v.zwwO(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), v.w(), c)));
BOOST_ASSERT((v.zwwx(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), v.w(), v.x())));
BOOST_ASSERT((v.zwwy(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), v.w(), v.y())));
BOOST_ASSERT((v.zwwz(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), v.w(), v.z())));
BOOST_ASSERT((v.zwww(c) == eagine::math::tvec<T,4,V>(v.z(), v.w(), v.w(), v.w())));
BOOST_ASSERT((v.wOOO(c) == eagine::math::tvec<T,4,V>(v.w(), c, c, c)));
BOOST_ASSERT((v.wOOx(c) == eagine::math::tvec<T,4,V>(v.w(), c, c, v.x())));
BOOST_ASSERT((v.wOOy(c) == eagine::math::tvec<T,4,V>(v.w(), c, c, v.y())));
BOOST_ASSERT((v.wOOz(c) == eagine::math::tvec<T,4,V>(v.w(), c, c, v.z())));
BOOST_ASSERT((v.wOOw(c) == eagine::math::tvec<T,4,V>(v.w(), c, c, v.w())));
BOOST_ASSERT((v.wOxO(c) == eagine::math::tvec<T,4,V>(v.w(), c, v.x(), c)));
BOOST_ASSERT((v.wOxx(c) == eagine::math::tvec<T,4,V>(v.w(), c, v.x(), v.x())));
BOOST_ASSERT((v.wOxy(c) == eagine::math::tvec<T,4,V>(v.w(), c, v.x(), v.y())));
BOOST_ASSERT((v.wOxz(c) == eagine::math::tvec<T,4,V>(v.w(), c, v.x(), v.z())));
BOOST_ASSERT((v.wOxw(c) == eagine::math::tvec<T,4,V>(v.w(), c, v.x(), v.w())));
BOOST_ASSERT((v.wOyO(c) == eagine::math::tvec<T,4,V>(v.w(), c, v.y(), c)));
BOOST_ASSERT((v.wOyx(c) == eagine::math::tvec<T,4,V>(v.w(), c, v.y(), v.x())));
BOOST_ASSERT((v.wOyy(c) == eagine::math::tvec<T,4,V>(v.w(), c, v.y(), v.y())));
BOOST_ASSERT((v.wOyz(c) == eagine::math::tvec<T,4,V>(v.w(), c, v.y(), v.z())));
BOOST_ASSERT((v.wOyw(c) == eagine::math::tvec<T,4,V>(v.w(), c, v.y(), v.w())));
BOOST_ASSERT((v.wOzO(c) == eagine::math::tvec<T,4,V>(v.w(), c, v.z(), c)));
BOOST_ASSERT((v.wOzx(c) == eagine::math::tvec<T,4,V>(v.w(), c, v.z(), v.x())));
BOOST_ASSERT((v.wOzy(c) == eagine::math::tvec<T,4,V>(v.w(), c, v.z(), v.y())));
BOOST_ASSERT((v.wOzz(c) == eagine::math::tvec<T,4,V>(v.w(), c, v.z(), v.z())));
BOOST_ASSERT((v.wOzw(c) == eagine::math::tvec<T,4,V>(v.w(), c, v.z(), v.w())));
BOOST_ASSERT((v.wOwO(c) == eagine::math::tvec<T,4,V>(v.w(), c, v.w(), c)));
BOOST_ASSERT((v.wOwx(c) == eagine::math::tvec<T,4,V>(v.w(), c, v.w(), v.x())));
BOOST_ASSERT((v.wOwy(c) == eagine::math::tvec<T,4,V>(v.w(), c, v.w(), v.y())));
BOOST_ASSERT((v.wOwz(c) == eagine::math::tvec<T,4,V>(v.w(), c, v.w(), v.z())));
BOOST_ASSERT((v.wOww(c) == eagine::math::tvec<T,4,V>(v.w(), c, v.w(), v.w())));
BOOST_ASSERT((v.wxOO(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), c, c)));
BOOST_ASSERT((v.wxOx(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), c, v.x())));
BOOST_ASSERT((v.wxOy(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), c, v.y())));
BOOST_ASSERT((v.wxOz(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), c, v.z())));
BOOST_ASSERT((v.wxOw(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), c, v.w())));
BOOST_ASSERT((v.wxxO(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), v.x(), c)));
BOOST_ASSERT((v.wxxx(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), v.x(), v.x())));
BOOST_ASSERT((v.wxxy(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), v.x(), v.y())));
BOOST_ASSERT((v.wxxz(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), v.x(), v.z())));
BOOST_ASSERT((v.wxxw(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), v.x(), v.w())));
BOOST_ASSERT((v.wxyO(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), v.y(), c)));
BOOST_ASSERT((v.wxyx(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), v.y(), v.x())));
BOOST_ASSERT((v.wxyy(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), v.y(), v.y())));
BOOST_ASSERT((v.wxyz(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), v.y(), v.z())));
BOOST_ASSERT((v.wxyw(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), v.y(), v.w())));
BOOST_ASSERT((v.wxzO(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), v.z(), c)));
BOOST_ASSERT((v.wxzx(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), v.z(), v.x())));
BOOST_ASSERT((v.wxzy(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), v.z(), v.y())));
BOOST_ASSERT((v.wxzz(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), v.z(), v.z())));
BOOST_ASSERT((v.wxzw(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), v.z(), v.w())));
BOOST_ASSERT((v.wxwO(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), v.w(), c)));
BOOST_ASSERT((v.wxwx(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), v.w(), v.x())));
BOOST_ASSERT((v.wxwy(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), v.w(), v.y())));
BOOST_ASSERT((v.wxwz(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), v.w(), v.z())));
BOOST_ASSERT((v.wxww(c) == eagine::math::tvec<T,4,V>(v.w(), v.x(), v.w(), v.w())));
BOOST_ASSERT((v.wyOO(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), c, c)));
BOOST_ASSERT((v.wyOx(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), c, v.x())));
BOOST_ASSERT((v.wyOy(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), c, v.y())));
BOOST_ASSERT((v.wyOz(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), c, v.z())));
BOOST_ASSERT((v.wyOw(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), c, v.w())));
BOOST_ASSERT((v.wyxO(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), v.x(), c)));
BOOST_ASSERT((v.wyxx(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), v.x(), v.x())));
BOOST_ASSERT((v.wyxy(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), v.x(), v.y())));
BOOST_ASSERT((v.wyxz(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), v.x(), v.z())));
BOOST_ASSERT((v.wyxw(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), v.x(), v.w())));
BOOST_ASSERT((v.wyyO(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), v.y(), c)));
BOOST_ASSERT((v.wyyx(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), v.y(), v.x())));
BOOST_ASSERT((v.wyyy(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), v.y(), v.y())));
BOOST_ASSERT((v.wyyz(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), v.y(), v.z())));
BOOST_ASSERT((v.wyyw(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), v.y(), v.w())));
BOOST_ASSERT((v.wyzO(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), v.z(), c)));
BOOST_ASSERT((v.wyzx(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), v.z(), v.x())));
BOOST_ASSERT((v.wyzy(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), v.z(), v.y())));
BOOST_ASSERT((v.wyzz(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), v.z(), v.z())));
BOOST_ASSERT((v.wyzw(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), v.z(), v.w())));
BOOST_ASSERT((v.wywO(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), v.w(), c)));
BOOST_ASSERT((v.wywx(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), v.w(), v.x())));
BOOST_ASSERT((v.wywy(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), v.w(), v.y())));
BOOST_ASSERT((v.wywz(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), v.w(), v.z())));
BOOST_ASSERT((v.wyww(c) == eagine::math::tvec<T,4,V>(v.w(), v.y(), v.w(), v.w())));
BOOST_ASSERT((v.wzOO(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), c, c)));
BOOST_ASSERT((v.wzOx(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), c, v.x())));
BOOST_ASSERT((v.wzOy(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), c, v.y())));
BOOST_ASSERT((v.wzOz(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), c, v.z())));
BOOST_ASSERT((v.wzOw(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), c, v.w())));
BOOST_ASSERT((v.wzxO(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), v.x(), c)));
BOOST_ASSERT((v.wzxx(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), v.x(), v.x())));
BOOST_ASSERT((v.wzxy(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), v.x(), v.y())));
BOOST_ASSERT((v.wzxz(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), v.x(), v.z())));
BOOST_ASSERT((v.wzxw(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), v.x(), v.w())));
BOOST_ASSERT((v.wzyO(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), v.y(), c)));
BOOST_ASSERT((v.wzyx(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), v.y(), v.x())));
BOOST_ASSERT((v.wzyy(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), v.y(), v.y())));
BOOST_ASSERT((v.wzyz(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), v.y(), v.z())));
BOOST_ASSERT((v.wzyw(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), v.y(), v.w())));
BOOST_ASSERT((v.wzzO(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), v.z(), c)));
BOOST_ASSERT((v.wzzx(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), v.z(), v.x())));
BOOST_ASSERT((v.wzzy(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), v.z(), v.y())));
BOOST_ASSERT((v.wzzz(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), v.z(), v.z())));
BOOST_ASSERT((v.wzzw(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), v.z(), v.w())));
BOOST_ASSERT((v.wzwO(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), v.w(), c)));
BOOST_ASSERT((v.wzwx(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), v.w(), v.x())));
BOOST_ASSERT((v.wzwy(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), v.w(), v.y())));
BOOST_ASSERT((v.wzwz(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), v.w(), v.z())));
BOOST_ASSERT((v.wzww(c) == eagine::math::tvec<T,4,V>(v.w(), v.z(), v.w(), v.w())));
BOOST_ASSERT((v.wwOO(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), c, c)));
BOOST_ASSERT((v.wwOx(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), c, v.x())));
BOOST_ASSERT((v.wwOy(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), c, v.y())));
BOOST_ASSERT((v.wwOz(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), c, v.z())));
BOOST_ASSERT((v.wwOw(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), c, v.w())));
BOOST_ASSERT((v.wwxO(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), v.x(), c)));
BOOST_ASSERT((v.wwxx(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), v.x(), v.x())));
BOOST_ASSERT((v.wwxy(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), v.x(), v.y())));
BOOST_ASSERT((v.wwxz(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), v.x(), v.z())));
BOOST_ASSERT((v.wwxw(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), v.x(), v.w())));
BOOST_ASSERT((v.wwyO(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), v.y(), c)));
BOOST_ASSERT((v.wwyx(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), v.y(), v.x())));
BOOST_ASSERT((v.wwyy(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), v.y(), v.y())));
BOOST_ASSERT((v.wwyz(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), v.y(), v.z())));
BOOST_ASSERT((v.wwyw(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), v.y(), v.w())));
BOOST_ASSERT((v.wwzO(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), v.z(), c)));
BOOST_ASSERT((v.wwzx(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), v.z(), v.x())));
BOOST_ASSERT((v.wwzy(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), v.z(), v.y())));
BOOST_ASSERT((v.wwzz(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), v.z(), v.z())));
BOOST_ASSERT((v.wwzw(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), v.z(), v.w())));
BOOST_ASSERT((v.wwwO(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), v.w(), c)));
BOOST_ASSERT((v.wwwx(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), v.w(), v.x())));
BOOST_ASSERT((v.wwwy(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), v.w(), v.y())));
BOOST_ASSERT((v.wwwz(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), v.w(), v.z())));
BOOST_ASSERT((v.wwww(c) == eagine::math::tvec<T,4,V>(v.w(), v.w(), v.w(), v.w())));
